import {
    getAppetizersPageRoute,
    getDessertsAndBakeryPageRoute,
    getDrinksPageRoute,
    getFirstCoursesPageRoute,
    getGrillDishesPageRoute,
    getKidsDishesPageRoute,
    getMainCoursesPageRoute,
    getNationalCuisinePageRoute,
    getPreservesPageRoute,
    getSaladsPageRoute,
    getSaucesPageRoute,
    getTherapeuticNutritionPageRoute,
    getVeganPageRoute,
} from '~/lib/routes';

import { IMenuItem } from './types';

export const MENU_ITEMS: IMenuItem[] = [
    {
        title: 'Салаты',
        iconUrl: '/icons/1.svg',
        subMenuItems: [
            {
                name: 'Мясные салаты',
                link: '/salads/meat',
                slug: 'meat',
                getRoute: () => getSaladsPageRoute({ slug: 'meat' }),
            },
            {
                name: 'Рыбные салаты',
                link: '/salads/fish',
                slug: 'fish',
                getRoute: () => getSaladsPageRoute({ slug: 'fish' }),
            },
            {
                name: 'Овощные салаты',
                link: '/salads/vegetable',
                slug: 'vegetable',
                getRoute: () => getSaladsPageRoute({ slug: 'vegetable' }),
            },
            {
                name: 'Теплые салаты',
                link: '/salads/warm',
                slug: 'warm',
                getRoute: () => getSaladsPageRoute({ slug: 'warm' }),
            },
        ],
    },
    {
        title: 'Закуски',
        iconUrl: '/icons/2.svg',
        subMenuItems: [
            {
                name: 'Мясные закуски',
                link: '/appetizers/meat',
                slug: 'warm',
                getRoute: () => getAppetizersPageRoute({ slug: 'warm' }),
            },
            {
                name: 'Рыбные закуски',
                link: '/appetizers/fish',
                slug: 'fish',
                getRoute: () => getAppetizersPageRoute({ slug: 'fish' }),
            },
            {
                name: 'Овощные закуски',
                link: '/appetizers/vegetable',
                slug: 'vegetable',
                getRoute: () => getAppetizersPageRoute({ slug: 'vegetable' }),
            },
            {
                name: 'Теплые закуски',
                link: '/appetizers/warm',
                slug: 'warm',
                getRoute: () => getAppetizersPageRoute({ slug: 'warm' }),
            },
            {
                name: 'Бутерброды',
                link: '/appetizers/sandwiches',
                slug: 'sandwiches',
                getRoute: () => getAppetizersPageRoute({ slug: 'sandwiches' }),
            },
            {
                name: 'Фастфуд',
                link: '/appetizers/fastfood',
                slug: 'fastfood',
                getRoute: () => getAppetizersPageRoute({ slug: 'fastfood' }),
            },
        ],
    },
    {
        title: 'Первые блюда',
        iconUrl: '/icons/3.svg',
        subMenuItems: [
            {
                name: 'Мясные супы',
                link: '/soups/meat',
                slug: 'meat',
                getRoute: () => getFirstCoursesPageRoute({ slug: 'meat' }),
            },
            {
                name: 'Овощные супы',
                link: '/soups/vegetable',
                slug: 'vegetable',
                getRoute: () => getFirstCoursesPageRoute({ slug: 'vegetable' }),
            },
            {
                name: 'Бульоны',
                link: '/soups/broth',
                slug: 'broth',
                getRoute: () => getFirstCoursesPageRoute({ slug: 'broth' }),
            },
            {
                name: 'Холодные супы',
                link: '/soups/cold',
                slug: 'cold',
                getRoute: () => getFirstCoursesPageRoute({ slug: 'cold' }),
            },
            {
                name: 'Диетические супы',
                link: '/soups/diet',
                slug: 'diet',
                getRoute: () => getFirstCoursesPageRoute({ slug: 'diet' }),
            },
        ],
    },
    {
        title: 'Вторые блюда',
        iconUrl: '/icons/4.svg',
        subMenuItems: [
            {
                name: 'Мясные',
                link: '/main-courses/meat',
                slug: 'meat',
                getRoute: () => getMainCoursesPageRoute({ slug: 'meat' }),
            },
            {
                name: 'Рыбные',
                link: '/main-courses/fish',
                slug: 'fish',
                getRoute: () => getMainCoursesPageRoute({ slug: 'fish' }),
            },
            {
                name: 'Овощные',
                link: '/main-courses/vegetable',
                slug: 'vegetable',
                getRoute: () => getMainCoursesPageRoute({ slug: 'vegetable' }),
            },
            {
                name: 'Из птицы',
                link: '/main-courses/poultry',
                slug: 'poultry',
                getRoute: () => getMainCoursesPageRoute({ slug: 'poultry' }),
            },
            {
                name: 'Из грибов',
                link: '/main-courses/mushrooms',
                slug: 'mushrooms',
                getRoute: () => getMainCoursesPageRoute({ slug: 'mushrooms' }),
            },
            {
                name: 'Из субпродуктов',
                link: '/main-courses/by-products',
                slug: 'by-products',
                getRoute: () => getMainCoursesPageRoute({ slug: 'by-products' }),
            },
            {
                name: 'На пару',
                link: '/main-courses/steamed',
                slug: 'steamed',
                getRoute: () => getMainCoursesPageRoute({ slug: 'steamed' }),
            },
            {
                name: 'Пельмени, вареники',
                link: '/main-courses/dumplings',
                slug: 'dumplings',
                getRoute: () => getMainCoursesPageRoute({ slug: 'dumplings' }),
            },
            {
                name: 'Мучные гарниры',
                link: '/main-courses/flour-side',
                slug: 'flour-side',
                getRoute: () => getMainCoursesPageRoute({ slug: 'flour-side' }),
            },
            {
                name: 'Овощные гарниры',
                link: '/main-courses/vegetable-side',
                slug: 'vegetable-side',
                getRoute: () => getMainCoursesPageRoute({ slug: 'vegetable-side' }),
            },
            {
                name: 'Пицца',
                link: '/main-courses/pizza',
                slug: 'pizza',
                getRoute: () => getMainCoursesPageRoute({ slug: 'pizza' }),
            },
            {
                name: 'Суши',
                link: '/main-courses/sushi',
                slug: 'sushi',
                getRoute: () => getMainCoursesPageRoute({ slug: 'sushi' }),
            },
        ],
    },
    {
        title: 'Десерты и выпечка',
        iconUrl: '/icons/5.svg',
        subMenuItems: [
            {
                name: 'Блины и оладьи',
                link: '/desserts/pancakes',
                slug: 'pancakes',
                getRoute: () => getDessertsAndBakeryPageRoute({ slug: 'pancakes' }),
            },
            {
                name: 'Пироги и пончики',
                link: '/desserts/pies',
                slug: 'pies',
                getRoute: () => getDessertsAndBakeryPageRoute({ slug: 'pies' }),
            },
            {
                name: 'Торты',
                link: '/desserts/cakes',
                slug: 'cakes',
                getRoute: () => getDessertsAndBakeryPageRoute({ slug: 'cakes' }),
            },
            {
                name: 'Рулеты',
                link: '/desserts/rolls',
                slug: 'rolls',
                getRoute: () => getDessertsAndBakeryPageRoute({ slug: 'rolls' }),
            },
            {
                name: 'Кексы и маффины',
                link: '/desserts/muffins',
                slug: 'muffins',
                getRoute: () => getDessertsAndBakeryPageRoute({ slug: 'muffins' }),
            },
            {
                name: 'Сырники и ватрушки',
                link: '/desserts/cheesecakes',
                slug: 'cheesecakes',
                getRoute: () => getDessertsAndBakeryPageRoute({ slug: 'cheesecakes' }),
            },
            {
                name: 'Из слоеного теста',
                link: '/desserts/puff-pastry',
                slug: 'puff-pastry',
                getRoute: () => getDessertsAndBakeryPageRoute({ slug: 'puff-pastry' }),
            },
            {
                name: 'Из заварного теста',
                link: '/desserts/choux-pastry',
                slug: 'choux-pastry',
                getRoute: () => getDessertsAndBakeryPageRoute({ slug: 'choux-pastry' }),
            },
            {
                name: 'Из дрожжевого теста',
                link: '/desserts/yeast-dough',
                slug: 'yeast-dough',
                getRoute: () => getDessertsAndBakeryPageRoute({ slug: 'yeast-dough' }),
            },
            {
                name: 'Булочки и сдоба',
                link: '/desserts/buns',
                slug: 'buns',
                getRoute: () => getDessertsAndBakeryPageRoute({ slug: 'buns' }),
            },
            {
                name: 'Хлеб',
                link: '/desserts/bread',
                slug: 'bread',
                getRoute: () => getDessertsAndBakeryPageRoute({ slug: 'bread' }),
            },
            {
                name: 'Тесто на пиццу',
                link: '/desserts/pizza-dough',
                slug: 'pizza-dough',
                getRoute: () => getDessertsAndBakeryPageRoute({ slug: 'pizza-dough' }),
            },
            {
                name: 'Кремы',
                link: '/desserts/creams',
                slug: 'creams',
                getRoute: () => getDessertsAndBakeryPageRoute({ slug: 'creams' }),
            },
        ],
    },
    {
        title: 'Блюда на гриле',
        iconUrl: '/icons/6.svg',
        subMenuItems: [
            {
                name: 'Говядина',
                link: '/grill/beef',
                slug: 'beef',
                getRoute: () => getGrillDishesPageRoute({ slug: 'beef' }),
            },
            {
                name: 'Свинина',
                link: '/grill/pork',
                slug: 'pork',
                getRoute: () => getGrillDishesPageRoute({ slug: 'pork' }),
            },
            {
                name: 'Птица',
                link: '/grill/poultry',
                slug: 'poultry',
                getRoute: () => getGrillDishesPageRoute({ slug: 'poultry' }),
            },
            {
                name: 'Рыба',
                link: '/grill/fish',
                slug: 'fish',
                getRoute: () => getGrillDishesPageRoute({ slug: 'fish' }),
            },
            {
                name: 'Грибы',
                link: '/grill/mushrooms',
                slug: 'mushrooms',
                getRoute: () => getGrillDishesPageRoute({ slug: 'mushrooms' }),
            },
            {
                name: 'Овощи',
                link: '/grill/vegetables',
                slug: 'vegetables',
                getRoute: () => getGrillDishesPageRoute({ slug: 'vegetables' }),
            },
        ],
    },
    {
        title: 'Веганская кухня',
        iconUrl: '/icons/7.svg',
        subMenuItems: [
            {
                name: 'Закуски',
                link: '/vegan/appetizers',
                slug: 'appetizers',
                getRoute: () => getVeganPageRoute({ slug: 'appetizers' }),
            },
            {
                name: 'Первые блюда',
                link: '/vegan/soups',
                slug: 'soups',
                getRoute: () => getVeganPageRoute({ slug: 'soups' }),
            },
            {
                name: 'Вторые блюда',
                link: '/vegan/main-courses',
                slug: 'main-courses',
                getRoute: () => getVeganPageRoute({ slug: 'main-courses' }),
            },
            {
                name: 'Гарниры',
                link: '/vegan/side-dishes',
                slug: 'side-dishes',
                getRoute: () => getVeganPageRoute({ slug: 'side-dishes' }),
            },
            {
                name: 'Десерты',
                link: '/vegan/desserts',
                slug: 'desserts',
                getRoute: () => getVeganPageRoute({ slug: 'desserts' }),
            },
            {
                name: 'Выпечка',
                link: '/vegan/bakery',
                slug: 'bakery',
                getRoute: () => getVeganPageRoute({ slug: 'bakery' }),
            },
            {
                name: 'Сыроедческие блюда',
                link: '/vegan/raw-food',
                slug: 'raw-food',
                getRoute: () => getVeganPageRoute({ slug: 'raw-food' }),
            },
            {
                name: 'Напитки',
                link: '/vegan/drinks',
                slug: 'drinks',
                getRoute: () => getVeganPageRoute({ slug: 'drinks' }),
            },
        ],
    },
    {
        title: 'Детские блюда',
        iconUrl: '/icons/8.svg',
        subMenuItems: [
            {
                name: 'Первые блюда',
                link: '/kids/soups',
                slug: 'soups',
                getRoute: () => getKidsDishesPageRoute({ slug: 'soups' }),
            },
            {
                name: 'Вторые блюда',
                link: '/kids/main-courses',
                slug: 'main-courses',
                getRoute: () => getKidsDishesPageRoute({ slug: 'main-courses' }),
            },
            {
                name: 'Гарниры',
                link: '/kids/side-dishes',
                slug: 'side-dishes',
                getRoute: () => getKidsDishesPageRoute({ slug: 'side-dishes' }),
            },
            {
                name: 'Выпечка',
                link: '/kids/bakery',
                slug: 'bakery',
                getRoute: () => getKidsDishesPageRoute({ slug: 'bakery' }),
            },
            {
                name: 'Без глютена',
                link: '/kids/gluten-free',
                slug: 'gluten-free',
                getRoute: () => getKidsDishesPageRoute({ slug: 'gluten-free' }),
            },
            {
                name: 'Без сахара',
                link: '/kids/sugar-free',
                slug: 'sugar-free',
                getRoute: () => getKidsDishesPageRoute({ slug: 'sugar-free' }),
            },
            {
                name: 'Без аллергенов',
                link: '/kids/allergen-free',
                slug: 'allergen-free',
                getRoute: () => getKidsDishesPageRoute({ slug: 'allergen-free' }),
            },
            {
                name: 'Блюда для прикорма',
                link: '/kids/first-foods',
                slug: 'first-foods',
                getRoute: () => getKidsDishesPageRoute({ slug: 'first-foods' }),
            },
        ],
    },
    {
        title: 'Лечебное питание',
        iconUrl: '/icons/9.svg',
        subMenuItems: [
            {
                name: 'Детская диета',
                link: '/diet/diet-kids',
                slug: 'diet-kids',
                getRoute: () => getTherapeuticNutritionPageRoute({ slug: 'diet-kids' }),
            },
            {
                name: 'Диета №1',
                link: '/diet/diet-1',
                slug: 'diet-1',
                getRoute: () => getTherapeuticNutritionPageRoute({ slug: 'diet-1' }),
            },
            {
                name: 'Диета №2',
                link: '/diet/diet-2',
                slug: 'diet-2',
                getRoute: () => getTherapeuticNutritionPageRoute({ slug: 'diet-2' }),
            },
            {
                name: 'Диета №3',
                link: '/diet/diet-3',
                slug: 'diet-3',
                getRoute: () => getTherapeuticNutritionPageRoute({ slug: 'diet-3' }),
            },
            {
                name: 'Диета №4',
                link: '/diet/diet-4',
                slug: 'diet-4',
                getRoute: () => getTherapeuticNutritionPageRoute({ slug: 'diet-4' }),
            },
            {
                name: 'Диета №5',
                link: '/diet/diet-5',
                slug: 'diet-5',
                getRoute: () => getTherapeuticNutritionPageRoute({ slug: 'diet-5' }),
            },
            {
                name: 'Диета №6',
                link: '/diet/diet-6',
                slug: 'diet-6',
                getRoute: () => getTherapeuticNutritionPageRoute({ slug: 'diet-6' }),
            },
            {
                name: 'Диета №7',
                link: '/diet/diet-7',
                slug: 'diet-7',
                getRoute: () => getTherapeuticNutritionPageRoute({ slug: 'diet-7' }),
            },
            {
                name: 'Диета №8',
                link: '/diet/diet-8',
                slug: 'diet-8',
                getRoute: () => getTherapeuticNutritionPageRoute({ slug: 'diet-8' }),
            },
        ],
    },
    {
        title: 'Национальные',
        iconUrl: '/icons/10.svg',
        subMenuItems: [
            {
                name: 'Американская кухня',
                link: '/national/american',
                slug: 'american',
                getRoute: () => getNationalCuisinePageRoute({ slug: 'american' }),
            },
            {
                name: 'Армянская кухня',
                link: '/national/armenian',
                slug: 'armenian',
                getRoute: () => getNationalCuisinePageRoute({ slug: 'armenian' }),
            },
            {
                name: 'Греческая кухня',
                link: '/national/greek',
                slug: 'greek',
                getRoute: () => getNationalCuisinePageRoute({ slug: 'greek' }),
            },
            {
                name: 'Грузинская кухня',
                link: '/national/georgian',
                slug: 'georgian',
                getRoute: () => getNationalCuisinePageRoute({ slug: 'georgian' }),
            },
            {
                name: 'Итальянская кухня',
                link: '/national/italian',
                slug: 'italian',
                getRoute: () => getNationalCuisinePageRoute({ slug: 'italian' }),
            },
            {
                name: 'Испанская кухня',
                link: '/national/spanish',
                slug: 'spanish',
                getRoute: () => getNationalCuisinePageRoute({ slug: 'spanish' }),
            },
            {
                name: 'Китайская кухня',
                link: '/national/chinese',
                slug: 'chinese',
                getRoute: () => getNationalCuisinePageRoute({ slug: 'chinese' }),
            },
            {
                name: 'Мексиканская кухня',
                link: '/national/mexican',
                slug: 'mexican',
                getRoute: () => getNationalCuisinePageRoute({ slug: 'mexican' }),
            },
            {
                name: 'Паназиатская кухня',
                link: '/national/pan-asian',
                slug: 'pan-asian',
                getRoute: () => getNationalCuisinePageRoute({ slug: 'pan-asian' }),
            },
            {
                name: 'Русская кухня',
                link: '/national/russian',
                slug: 'russian',
                getRoute: () => getNationalCuisinePageRoute({ slug: 'russian' }),
            },
            {
                name: 'Турецкая кухня',
                link: '/national/turkish',
                slug: 'turkish',
                getRoute: () => getNationalCuisinePageRoute({ slug: 'turkish' }),
            },
            {
                name: 'Французская кухня',
                link: '/national/french',
                slug: 'french',
                getRoute: () => getNationalCuisinePageRoute({ slug: 'french' }),
            },
            {
                name: 'Шведская кухня',
                link: '/national/swedish',
                slug: 'swedish',
                getRoute: () => getNationalCuisinePageRoute({ slug: 'swedish' }),
            },
            {
                name: 'Японская кухня',
                link: '/national/japanese',
                slug: 'japanese',
                getRoute: () => getNationalCuisinePageRoute({ slug: 'japanese' }),
            },
            {
                name: 'Другая кухня',
                link: '/national/other',
                slug: 'other',
                getRoute: () => getNationalCuisinePageRoute({ slug: 'other' }),
            },
        ],
    },
    {
        title: 'Соусы',
        iconUrl: '/icons/11.svg',
        subMenuItems: [
            {
                name: 'Соусы мясные',
                link: '/sauces/meat',
                slug: 'meat',
                getRoute: () => getSaucesPageRoute({ slug: 'meat' }),
            },
            {
                name: 'Соусы сырные',
                link: '/sauces/cheese',
                slug: 'cheese',
                getRoute: () => getSaucesPageRoute({ slug: 'cheese' }),
            },
            {
                name: 'Маринады',
                link: '/sauces/marinades',
                slug: 'marinades',
                getRoute: () => getSaucesPageRoute({ slug: 'marinades' }),
            },
        ],
    },
    {
        title: 'Заготовки',
        iconUrl: '/icons/13.svg',
        subMenuItems: [
            {
                name: 'Мясные заготовки',
                link: '/preserves/meat',
                slug: 'meat',
                getRoute: () => getPreservesPageRoute({ slug: 'meat' }),
            },
            {
                name: 'Рыбные заготовки',
                link: '/preserves/fish',
                slug: 'fish',
                getRoute: () => getPreservesPageRoute({ slug: 'fish' }),
            },
            {
                name: 'Из огурцов',
                link: '/preserves/cucumbers',
                slug: 'cucumbers',
                getRoute: () => getPreservesPageRoute({ slug: 'cucumbers' }),
            },
            {
                name: 'Из томатов',
                link: '/preserves/tomatoes',
                slug: 'tomatoes',
                getRoute: () => getPreservesPageRoute({ slug: 'tomatoes' }),
            },
            {
                name: 'Из грибов',
                link: '/preserves/mushrooms',
                slug: 'mushrooms',
                getRoute: () => getPreservesPageRoute({ slug: 'mushrooms' }),
            },
            {
                name: 'Овощные заготовки',
                link: '/preserves/vegetables',
                slug: 'vegetables',
                getRoute: () => getPreservesPageRoute({ slug: 'vegetables' }),
            },
            {
                name: 'Салаты, икра',
                link: '/preserves/salads',
                slug: 'salads',
                getRoute: () => getPreservesPageRoute({ slug: 'salads' }),
            },
            {
                name: 'Из фруктов и ягод',
                link: '/preserves/fruits',
                slug: 'fruits',
                getRoute: () => getPreservesPageRoute({ slug: 'fruits' }),
            },
        ],
    },
    {
        title: 'Напитки',
        iconUrl: '/icons/12.svg',
        subMenuItems: [
            {
                name: 'Соки и фреши',
                link: '/drinks/juices',
                slug: 'juices',
                getRoute: () => getDrinksPageRoute({ slug: 'juices' }),
            },
            {
                name: 'Смузи',
                link: '/drinks/smoothies',
                slug: 'smoothies',
                getRoute: () => getDrinksPageRoute({ slug: 'smoothies' }),
            },
            {
                name: 'Компоты',
                link: '/drinks/compotes',
                slug: 'compotes',
                getRoute: () => getDrinksPageRoute({ slug: 'compotes' }),
            },
            {
                name: 'Кисели',
                link: '/drinks/kissels',
                slug: 'kissels',
                getRoute: () => getDrinksPageRoute({ slug: 'kissels' }),
            },
            {
                name: 'Кофе',
                link: '/drinks/coffee',
                slug: 'coffee',
                getRoute: () => getDrinksPageRoute({ slug: 'coffee' }),
            },
            {
                name: 'Лечебный чай',
                link: '/drinks/tea',
                slug: 'tea',
                getRoute: () => getDrinksPageRoute({ slug: 'tea' }),
            },
            {
                name: 'Квас',
                link: '/drinks/kvass',
                slug: 'kvass',
                getRoute: () => getDrinksPageRoute({ slug: 'kvass' }),
            },
            {
                name: 'Коктейли',
                link: '/drinks/cocktails',
                slug: 'cocktails',
                getRoute: () => getDrinksPageRoute({ slug: 'cocktails' }),
            },
            {
                name: 'Алкогольные',
                link: '/drinks/alcohol',
                slug: 'alcohol',
                getRoute: () => getDrinksPageRoute({ slug: 'alcohol' }),
            },
        ],
    },
];
