export const NAME_MATCHER = {
    '/salads': 'Салаты',
    '/salads/meat': 'Мясные салаты',
    '/salads/fish': 'Рыбные салаты',
    '/salads/vegetable': 'Овощные салаты',
    '/salads/warm': 'Теплые салаты',
    '/appetizers': 'Закуски',
    '/appetizers/meat': 'Мясные закуски',
    '/appetizers/fish': 'Рыбные закуски',
    '/appetizers/vegetable': 'Овощные закуски',
    '/appetizers/warm': 'Теплые закуски',
    '/appetizers/sandwiches': 'Бутерброды',
    '/appetizers/fastfood': 'Фастфуд',
    '/soups': 'Первые блюда',
    '/soups/meat': 'Мясные супы',
    '/soups/vegetable': 'Овощные супы',
    '/soups/broth': 'Бульоны',
    '/soups/cold': 'Холодные супы',
    '/soups/diet': 'Диетические супы',
    '/main-courses': 'Вторые блюда',
    '/main-courses/meat': 'Мясные',
    '/main-courses/fish': 'Рыбные',
    '/main-courses/vegetable': 'Овощные',
    '/main-courses/poultry': 'Из птицы',
    '/main-courses/mushrooms': 'Из грибов',
    '/main-courses/by-products': 'Из субпродуктов',
    '/main-courses/steamed': 'На пару',
    '/main-courses/dumplings': 'Пельмени, вареники',
    '/main-courses/flour-side': 'Мучные гарниры',
    '/main-courses/vegetable-side': 'Овощные гарниры',
    '/main-courses/pizza': 'Пицца',
    '/main-courses/sushi': 'Суши',
    '/desserts': 'Десерты и выпечка',
    '/desserts/pancakes': 'Блины и оладьи',
    '/desserts/pies': 'Пироги и пончики',
    '/desserts/cakes': 'Торты',
    '/desserts/rolls': 'Рулеты',
    '/desserts/muffins': 'Кексы и маффины',
    '/desserts/cheesecakes': 'Сырники и ватрушки',
    '/desserts/puff-pastry': 'Из слоеного теста',
    '/desserts/choux-pastry': 'Из заварного теста',
    '/desserts/yeast-dough': 'Из дрожжевого теста',
    '/desserts/buns': 'Булочки и сдоба',
    '/desserts/bread': 'Хлеб',
    '/desserts/pizza-dough': 'Тесто на пиццу',
    '/desserts/creams': 'Кремы',
    '/grill': 'Блюда на гриле',
    '/grill/beef': 'Говядина',
    '/grill/pork': 'Свинина',
    '/grill/poultry': 'Птица',
    '/grill/fish': 'Рыба',
    '/grill/mushrooms': 'Грибы',
    '/grill/vegetables': 'Овощи',
    '/vegan': 'Веганская кухня',
    '/vegan/appetizers': 'Закуски',
    '/vegan/soups': 'Первые блюда',
    '/vegan/main-courses': 'Вторые блюда',
    '/vegan/side-dishes': 'Гарниры',
    '/vegan/desserts': 'Десерты',
    '/vegan/bakery': 'Выпечка',
    '/vegan/raw-food': 'Сыроедческие блюда',
    '/vegan/drinks': 'Напитки',
    '/kids': 'Детская кухня',
    '/kids/soups': 'Первые блюда',
    '/kids/main-courses': 'Вторые блюда',
    '/kids/side-dishes': 'Гарниры',
    '/kids/bakery': 'Выпечка',
    '/kids/gluten-free': 'Без глютена',
    '/kids/sugar-free': 'Без сахара',
    '/kids/allergen-free': 'Без аллергенов',
    '/kids/first-foods': 'Блюда для прикорма',
    '/diet': 'Лечебное питание',
    '/diet/diet-kids': 'Детская диета',
    '/diet/diet-1': 'Диета №1',
    '/diet/diet-2': 'Диета №2',
    '/diet/diet-3': 'Диета №3',
    '/diet/diet-4': 'Диета №4',
    '/diet/diet-5': 'Диета №5',
    '/diet/diet-6': 'Диета №6',
    '/diet/diet-7': 'Диета №7',
    '/diet/diet-8': 'Диета №8',
    '/diet/diet-9': 'Диета №9',
    '/diet/diet-10': 'Диета №10',
    '/diet/diet-11': 'Диета №11',
    '/diet/diet-12': 'Диета №12',
    '/diet/diet-13': 'Диета №13',
    '/diet/diet-14': 'Диета №14',
    '/diet/gluten-free': 'Без глютена',
    '/diet/allergen-free': 'Без аллергенов',
    '/national': 'Национальные блюда',
    '/national/american': 'Американская кухня',
    '/national/armenian': 'Армянская кухня',
    '/national/greek': 'Греческая кухня',
    '/national/georgian': 'Грузинская кухня',
    '/national/italian': 'Итальянская кухня',
    '/national/spanish': 'Испанская кухня',
    '/national/chinese': 'Китайская кухня',
    '/national/mexican': 'Мексиканская кухня',
    '/national/pan-asian': 'Паназиатская кухня',
    '/national/russian': 'Русская кухня',
    '/national/turkish': 'Турецкая кухня',
    '/national/french': 'Французская кухня',
    '/national/swedish': 'Шведская кухня',
    '/national/japanese': 'Японская кухня',
    '/national/other': 'Другая кухня',
    '/sauces': 'Соусы',
    '/sauces/meat': 'Соусы мясные',
    '/sauces/cheese': 'Соусы сырные',
    '/sauces/marinades': 'Маринады',
    '/preserves': 'Домашние заготовки',
    '/preserves/meat': 'Мясные заготовки',
    '/preserves/fish': 'Рыбные заготовки',
    '/preserves/cucumbers': 'Из огурцов',
    '/preserves/tomatoes': 'Из томатов',
    '/preserves/mushrooms': 'Из грибов',
    '/preserves/vegetables': 'Овощные заготовки',
    '/preserves/salads': 'Салаты, икра',
    '/preserves/fruits': 'Из фруктов и ягод',
    '/drinks': 'Напитки',
    '/drinks/juices': 'Соки и фреши',
    '/drinks/smoothies': 'Смузи',
    '/drinks/compotes': 'Компоты',
    '/drinks/kissels': 'Кисели',
    '/drinks/coffee': 'Кофе',
    '/drinks/tea': 'Лечебный чай',
    '/drinks/kvass': 'Квас',
    '/drinks/cocktails': 'Коктейли',
    '/drinks/alcohol': 'Алкогольные',
};
